server:
  port: 8989
  context-path: /springboot_mapper

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
mybatis:
  type-aliases-package: com.baizhi.wcj.entity
